---
- name: Install pip packages
  hosts: all
  become: yes  # Use this if you need superuser privileges
  vars:
    pip_packages:
      - requests
      - flask
      - numpy

  tasks:
    - name: Ensure pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install Python packages with pip
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop: "{{ pip_packages }}"
